image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - maximedenes.vscoq

tasks:
  - command: >
      eval $(opam env)
      && bash ./README.md
      && bash ./README.md  > ./README2.md
      && (coqide Tactics.v &)
      && code README2.md
      && bash ./README.md

ports:
  # vnc port
  - port: 6080
    onOpen: open-browser
